name: rim2d_tools
channels:
  - conda-forge
dependencies:
  - python=3.11.*
  - numpy
  - pandas
  - scipy
  - pytest=7.4.*
  - matplotlib=3.7.*
  - openpyxl
  - rasterio=1.3.*
  - geopandas=0.13.*
  - xarray=2023.7.*
  - rioxarray=0.14.*
  - dask=2023.7.*
  - netCDF4
  - flox
  - seaborn
  - pip
  - pip:
    - graphviz
    - sparse
